### ISSUE TITLE
Payment receipts

### ISSUE THREAD

**Issue by schmijos** [notionparallax/wp2frontEnd#36]
My WaldenPond gets paid by the company I work for (lucky me 😄 ). And since I pay for it with the company credit card, it would be nice to receive payment receipts per email (so that I can redirect them to finance automatically) or to pay on a yearly basis to reduce my admin overhead.

**Comment by notionparallax** [comment]
I'll have a look at how to set this up globally, but I'm pretty sure I can turn it on in the stripe dashboard just for you.

**Comment by notionparallax** [comment]
@schmijos I've turned on recipts for payments, I wonder what everyone will do when they start getting them?

**Comment by schmijos** [comment]
Very nice! Thank you!
